const {
  REACT_APP_GMAPS_API_KEY,
  REACT_APP_SHIPPYPRO_API_TOKEN,
  REACT_APP_SHIPPYPRO_API_ENDPOINT,
  REACT_APP_CURRENCY_SYMBOL,
} = process.env;

export const GMAPS_API_KEY: string = REACT_APP_GMAPS_API_KEY!;
export const SHIPPYPRO_API_TOKEN: string = REACT_APP_SHIPPYPRO_API_TOKEN!;
export const SHIPPYPRO_API_ENDPOINT: string = REACT_APP_SHIPPYPRO_API_ENDPOINT!;
export const CURRENCY_SYMBOL: string = REACT_APP_CURRENCY_SYMBOL!;
