const {
  REACT_APP_GMAPS_API_KEY,
  REACT_APP_SHIPPYPRO_API_TOKEN,
  REACT_APP_SHIPPYPRO_API_ENDPOINT,
  REACT_APP_CURRENCY_SYMBOL,
  REACT_APP_DEFAULT_MAP_ZOOM,
  REACT_APP_DEBUG_MAP,
  REACT_APP_ENABLE_MAP_SCROLL_ZOOM,
} = process.env;

export const GMAPS_API_KEY: string = REACT_APP_GMAPS_API_KEY!;
export const SHIPPYPRO_API_TOKEN: string = REACT_APP_SHIPPYPRO_API_TOKEN!;
export const SHIPPYPRO_API_ENDPOINT: string = REACT_APP_SHIPPYPRO_API_ENDPOINT!;
export const CURRENCY_SYMBOL: string = REACT_APP_CURRENCY_SYMBOL!;
export const DEFAULT_MAP_ZOOM: number = +REACT_APP_DEFAULT_MAP_ZOOM!;
export const DEBUG_MAP: boolean = Boolean(+REACT_APP_DEBUG_MAP!);
export const ENABLE_MAP_SCROLL_ZOOM: boolean = Boolean(+REACT_APP_ENABLE_MAP_SCROLL_ZOOM!);
